log_sources:
    - "/srv/topdata-nginx-proxy-v2/vol/nginx_logs/access.log"
block_log_output: "/srv/topdata-nginx-proxy-v2/vol/nginx_logs/ip-sentry-blocks.log"
heartbeat_stats_output: "/srv/topdata-nginx-proxy-v2/vol/nginx_logs/ip-sentry-heartbeat-stats.log"
fail2ban_config_path: "/srv/topdata-nginx-proxy-v2/vol/fail2ban"
geoip_db_path: "./data/geoip/GeoLite2-City.mmdb"

thresholds:
    # Lowered to 30 for testing to catch scrapers quickly
    max_requests_per_minute: 200

blacklist:
    countries: [ "CN", "RU", "IN", "IR", "SG", "SA", "AE", "QA", "KW", "BH", "OM", "IL", "US", "BR", "ID", "TR", "VN", "PK", "UA", "HK", "CA" ]
    hostnames:
        - ".amazonaws.com"
        - ".compute.internal"
        - ".googleusercontent.com"
        - ".hetzner."
        - ".ovh."
        - ".digitalocean."
        - ".linode."
        - ".as2116.net" # Common bot hosting

whitelist:
    hostnames:
        - ".googlebot.com"
        - ".search.msn.com"
        - ".uptimerobot.com"
    ips:
        - "192.168.1.100"
        - "10.0.0.50"
        - "172.16.0.25"
